import React from 'react';

function BodyThree() {

    return(
        <div className="bodyThree">
            <div className="starContainer">
                <div className="starImage"></div>
                <p className="info">A celestial body that generates light and other radiant energy and consists of a mass of gas held together by its own gravity in which the energy generated by nuclear reactions in the interior is balanced by the outflow of energy to the surface, and the inward-directed gravitational forces are balanced by the outward-directed gas and radiation pressures.</p>
            </div>
        </div>
    )
}

export {BodyThree}