import React from 'react';

function BodyThree() {

    return(
        <div className="bodyThree">
            <div className="starContainer">
                <div className="starImage"></div>
                <p className="info">A celestial body that generates light and other radiant energy and consists of a mass of gas held together by its own gravity in which the energy generated by nuclear reactions in the interior is balanced by the outflow of energy to the surface, and the inward-directed gravitational forces are balanced by the outward-directed gas and radiation pressures. A star is a luminous spheroid of plasma held together by self-gravity. The nearest star to Earth is the Sun. Many other stars are visible to the naked eye at night; their immense distances from Earth make them appear as fixed points of light. The most prominent stars have been categorised into constellations and asterisms, and many of the brightest stars have proper names.</p>
            </div>
        </div>
    )
}

export {BodyThree}